/* vtab_registry.h — C++ Virtual Table Registry Framework */
#pragma once
#ifndef SVDB_VTAB_REGISTRY_H
#define SVDB_VTAB_REGISTRY_H

#include <string>
#include <vector>
#include <memory>
#include <unordered_map>
#include <mutex>
#include <cstdint>

namespace svdb {

/* Forward declarations */
class VTabCursor;
class VTab;
class VTabModule;

/**
 * VTabCursor — Abstract base class for virtual table cursors
 * 
 * Cursors iterate through virtual table rows. Each cursor maintains
 * its own state and position.
 */
class VTabCursor {
public:
    virtual ~VTabCursor() = default;
    
    /**
     * Filter the cursor based on index and constraints
     * @param idxNum Index number (0 = no index)
     * @param idxStr Index constraint string
     * @param args Filter arguments
     * @return 0 on success, non-zero on error
     */
    virtual int Filter(int idxNum, const std::string& idxStr, 
                      const std::vector<std::string>& args) = 0;
    
    /**
     * Advance to next row
     * @return 0 on success, non-zero on error
     */
    virtual int Next() = 0;
    
    /**
     * Check if cursor is at end
     * @return true if no more rows
     */
    virtual bool Eof() const = 0;
    
    /**
     * Get column value at current row
     * @param col Column index (0-based)
     * @param out_type Output: value type (0=NULL, 1=INT, 2=REAL, 3=TEXT, 4=BLOB)
     * @param out_ival Output: integer value
     * @param out_rval Output: real value
     * @param out_sval Output: string/blob value
     * @param out_slen Output: string/blob length
     * @return 0 on success, non-zero on error
     */
    virtual int Column(int col, int* out_type, int64_t* out_ival, 
                      double* out_rval, const char** out_sval, 
                      size_t* out_slen) = 0;
    
    /**
     * Get current row ID
     * @param out_rowid Output: row ID
     * @return 0 on success, non-zero on error
     */
    virtual int RowID(int64_t* out_rowid) = 0;
    
    /**
     * Close cursor and free resources
     * @return 0 on success, non-zero on error
     */
    virtual int Close() = 0;
};

/**
 * VTab — Abstract base class for virtual tables
 * 
 * Virtual tables are dynamic tables generated by modules. They can be
 * created permanently (CREATE VIRTUAL TABLE) or transiently (table functions).
 */
class VTab {
public:
    virtual ~VTab() = default;
    
    /**
     * Get column names for this virtual table
     * @return Vector of column names
     */
    virtual std::vector<std::string> Columns() const = 0;
    
    /**
     * Open a cursor on this virtual table
     * @return New cursor instance, or nullptr on error
     */
    virtual VTabCursor* Open() = 0;
    
    /**
     * Get best index for query optimization (optional)
     * @param constraints Query constraints
     * @param out_idxNum Output: index number
     * @param out_idxStr Output: index string
     * @param out_estimated_rows Output: estimated row count
     * @param out_estimated_cost Output: estimated cost
     * @return 0 on success, non-zero on error
     */
    virtual int BestIndex(const std::vector<int>& constraints,
                         int* out_idxNum, std::string* out_idxStr,
                         int64_t* out_estimated_rows,
                         double* out_estimated_cost) {
        (void)constraints;
        (void)out_idxNum;
        (void)out_idxStr;
        (void)out_estimated_rows;
        (void)out_estimated_cost;
        return 0; /* No index by default */
    }
    
    /**
     * Disconnect from virtual table (for permanent vtabs)
     * @return 0 on success, non-zero on error
     */
    virtual int Disconnect() { return 0; }
    
    /**
     * Destroy virtual table (for permanent vtabs)
     * @return 0 on success, non-zero on error
     */
    virtual int Destroy() { return 0; }
};

/**
 * VTabModule — Abstract base class for virtual table modules
 * 
 * Modules are factories that create virtual tables. Each module
 * defines the schema and behavior of a specific type of virtual table.
 */
class VTabModule {
public:
    virtual ~VTabModule() = default;
    
    /**
     * Create a new permanent virtual table
     * @param args Module arguments from CREATE VIRTUAL TABLE
     * @return New VTab instance, or nullptr on error
     */
    virtual VTab* Create(const std::vector<std::string>& args) = 0;
    
    /**
     * Connect to a transient virtual table (table function)
     * @param args Module arguments from table function call
     * @return New VTab instance, or nullptr on error
     */
    virtual VTab* Connect(const std::vector<std::string>& args) = 0;
};

/**
 * VTabRegistry — Singleton registry for virtual table modules
 * 
 * Manages registration and lookup of virtual table modules.
 * Thread-safe for concurrent access.
 * 
 * Note: The registry does NOT take ownership of registered modules.
 * Modules must outlive the registry (typically static/global lifetime).
 */
class VTabRegistry {
public:
    /**
     * Get singleton instance
     * @return Reference to singleton registry
     */
    static VTabRegistry& Instance();
    
    /**
     * Register a virtual table module
     * @param name Module name (case-insensitive)
     * @param module Module instance (must outlive registry)
     * @return 0 on success, non-zero on error
     */
    int RegisterModule(const std::string& name, VTabModule* module);
    
    /**
     * Get a registered module by name
     * @param name Module name (case-insensitive)
     * @return Module instance, or nullptr if not found
     */
    VTabModule* GetModule(const std::string& name);
    
    /**
     * Unregister a module (does not delete the module)
     * @param name Module name (case-insensitive)
     * @return 0 on success, non-zero if not found
     */
    int UnregisterModule(const std::string& name);
    
    /**
     * Check if a module is registered
     * @param name Module name (case-insensitive)
     * @return true if registered
     */
    bool HasModule(const std::string& name);
    
    /**
     * Get all registered module names
     * @return Vector of module names
     */
    std::vector<std::string> GetModuleNames();

private:
    VTabRegistry() = default;
    ~VTabRegistry() = default;
    
    VTabRegistry(const VTabRegistry&) = delete;
    VTabRegistry& operator=(const VTabRegistry&) = delete;
    
    std::unordered_map<std::string, VTabModule*> modules_;
    std::mutex mutex_;
};

/**
 * Helper: Register a module at static initialization time
 * 
 * Usage in module implementation:
 *   static auto registered = svdb::RegisterModule("series", new SeriesModule());
 */
struct RegisterModule {
    RegisterModule(const std::string& name, VTabModule* module) {
        VTabRegistry::Instance().RegisterModule(name, module);
    }
};

} /* namespace svdb */

#endif /* SVDB_VTAB_REGISTRY_H */
